### ISSUE TITLE
Placeholder not showing 

### ISSUE THREAD

**Issue by filippoveggo** [riccardocalligaro/registro_elettronico#1]
![Cattura](https://user-images.githubusercontent.com/33131807/72358132-5e454080-36ec-11ea-9a07-2c1588e943be.PNG)

**Comment by ghost** [comment]
@filippoveggo Buongiorno! Avrei bisogno di parlarti, in merito a questa richiesta. Posso parlarti in privato? Mi scrivi alla mia mail: padovesi.roberto@gmail.com? Grazie!
